[platformio]
default_envs = engine_ecu, torque_logger_ecu

[env]
platform = espressif32@7.1.2
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -std=gnu++17
  -D CAN_TX_PIN=5
  -D CAN_RX_PIN=4
  -D CAN_BITRATE=500000

[env:engine_ecu]
build_src_filter = +<common/> +<engine_ecu/>
build_flags = ${env.build_flags} -D NODE_ENGINE=1

[env:torque_logger_ecu]
build_src_filter = +<common/> +<torque_logger_ecu/>
build_flags =
  ${env.build_flags}
  -D NODE_TORQUE_LOGGER=1
  -D ENABLE_SD_LOG=0
  -D SD_CS_PIN=13

[env:torque_logger_ecu_sd]
build_src_filter = +<common/> +<torque_logger_ecu/>
build_flags =
  ${env.build_flags}
  -D NODE_TORQUE_LOGGER=1
  -D ENABLE_SD_LOG=1
  -D SD_CS_PIN=13
